Feat ts support
zoopit/amqp-helper pull request #2
Opened 2022-06-09 22:05 UTC by babak-zoopit

### what
- [x] my commit messages describe the changes and comply to [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/)
A js and a declaration file added to the module.
semantic release also added

### why

To be able to use it in typescript codes.

### side notes

I prefer this way to leave index completely unchanged.

2022-06-10 09:24 UTC, Smembe812 requested changes
could you remove the `on pull_request event` block because the `on push event` also listens to pull requests

2022-06-10 09:29 UTC, Smembe812 requested changes
https://github.com/zoopit/amqp-helper/pull/2/commits/93e975ef90e69ead37b459086a7f9bff0b4d0796

could you try using [util.promisify](https://nodejs.org/api/util.html#utilpromisifyoriginal) instead of Promise((resolve, reject))? Other wise it should be fine how it is now

2022-06-10 09:31 UTC, Smembe812 reviewed
> could you remove the `on pull_request event` block because the `on push event` also listens to pull requests

I see you have already removed it in 0d48ec80defc7939355647d2d514dffbaeeda362 @babak-zoopit 👍

2022-06-10 14:17 UTC, ilibar-zpt commented
why did you specify branches in CI and semantic release?

2022-06-10 14:44 UTC, ilibar-zpt commented on .github/workflows/ci.yml
> +          node-version: '16'
any reason to not use 18?

2022-06-10 14:47 UTC, ilibar-zpt commented on package.json
>    "main": "src/index.js",
this one needs a change, and if d.ts has same basename then you don't need `types` key

2022-06-13 08:51 UTC, babak-zoopit commented on .github/workflows/ci.yml
> +          node-version: '16'
https://nodejs.org/en/

16 is recommended for most users right now.
I can change it.
Let me know if it's better to do it.

2022-06-13 08:52 UTC, babak-zoopit commented on package.json
>    "main": "src/index.js",
Good information.
I'll check and remove it.

2022-06-13 09:14 UTC, babak-zoopit commented
> why did you specify branches in CI and semantic release?

In CI:
To keep sync only master with registry.

In releaserc.json:
I got error without specifying branches (however [here](https://github.com/semantic-release/semantic-release/blob/HEAD/docs/usage/configuration.md#branches) specified that branches has a default value)

2022-06-13 11:16 UTC, ilibar-zpt commented
> In CI:
> To keep sync only master with registry.

then how are we supposed to know if CI checks pass on your PR?

> In releaserc.json:

should not change it
what was the error? feel free to ask next time

2022-06-13 11:22 UTC, ilibar-zpt commented on .github/workflows/ci.yml
> +          node-version: '16'
I'd upgrade now

2022-06-14 12:46 UTC, ilibar-zpt commented on .github/workflows/ci.yml
> +      - run: npm ci
include `npm audit --audit-level=high` step before `ci`

2022-06-14 12:48 UTC, ilibar-zpt commented
consider adding `.editorconfig` for consistency

2022-06-16 09:03 UTC, Smembe812 approved these changes
Could you add some example of how to use it like how you did in https://github.com/zoopit/routing/blob/init-api/api/test/test-helper/amqp.js? Otherwise, it looks fine to me

2022-06-16 14:49 UTC, ilibar-zpt commented on package.json
>      "test": "mocha"
include TS declaration validation to the test

2022-06-16 14:50 UTC, ilibar-zpt requested changes
comments to be adressed

2022-06-20 14:27 UTC, ilibar-zpt requested changes

2022-06-20 14:27 UTC, ilibar-zpt commented on .github/workflows/ci.yml
> +          node-version: '16'
any changes? there's old unresolved comment

2022-06-20 14:27 UTC, ilibar-zpt commented on package.json
>    "main": "src/index.js",
any changes? there's old unresolved comment

2022-06-20 14:27 UTC, ilibar-zpt commented on package.json
> +    "mocha": "^10.0.0",
why is it a production dependency?

2022-06-20 14:27 UTC, ilibar-zpt commented on package.json
> +    "test": "tsc src/ts-support.d.ts; mocha "
why `;`?

2022-06-20 14:27 UTC, ilibar-zpt commented on src/ts-support.d.ts
> +export type Connection = Connection1
```suggestion
import type * as AMQP from "amqplib" 

// Just declaration file for ts-support.js


export function connect(uri: string): Promise<AMQP.Connection>;

export function sendWithResponseQueue<T,R>(connection: AMQP.Connection , queueOut: string , queueIn: string , body: T): Promise<R>;

export type Connection = AMQP.Connection
```

2022-06-20 14:55 UTC, babak-zoopit commented on package.json
>    "main": "src/index.js",
had removed in this commit: [e570070](https://github.com/zoopit/amqp-helper/pull/2/commits/e5700708740cc86d80b4a5b776560250a1e09feb)

2022-06-22 11:54 UTC, Smembe812 commented
Maybe close the PR @babak-zoopit ?

2022-06-27 23:47 UTC, ilibar-zpt commented
closed in favor of https://github.com/zoopit/amqp-helper-ts/pull/1

2022-06-27 23:47 UTC, closed without merging